export { default as MetaTags } from './MetaTags';
export { default as Title } from './Title';
export { default as Description } from './Description';
export { default as DefaultSEO } from './DefaultSEO';
export { default as HomeSEO } from './HomeSEO';
export { default as WorkDetailSEO } from './WorkDetailSEO';
export { default as ContactSEO } from './ContactSEO';
export { default as PageSEO } from './PageSEO';
export { default as SEOProvider } from './SEOProvider';